### ISSUE TITLE
question on the Param

### ISSUE THREAD

**Issue by ace34568** [o365soa/Scripts#1]
I'm getting error code: 

Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmbiguousParameterSet

**Comment by sbueffel** [comment]
You did not indicate which script you are running that resulted in the error.  Please provide that and the parameters you are using and we can help resolve.
