### ISSUE TITLE
PIM Active Roles shown only

### ISSUE THREAD

**Issue by adsweeny** [o365soa/Scripts#19]
This report seems to only evaluate PIM active roles, not eligible members that are not currently activated.  Could it include those in the future?

**Comment by McDoMaster** [comment]
Hey,
You should use Graph API to get the members using the command : `Get-MgRoleManagementDirectoryRoleEligibilityScheduleInstance`

[Get-MgRoleManagementDirectoryRoleEligibilityScheduleInstance - Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.enrolment/get-mgrolemanagementdirectoryroleeligibilityscheduleinstance?view=graph-powershell-1.0)

You can loop the results and filter the groups and users

**Comment by sbueffel** [comment]
Yes, we will add that to our feature request list. The script needs to be updated to move the MSOnline dependencies to Graph PowerShell SDK, at which time we can explore including eligible role members. If we don't add it then, we will put it on our feature request backlog.
