### ISSUE TITLE
invoke-mggraph cmdlet no longer has -authentication param. Unable to run script

### ISSUE THREAD

**Issue by csozMSFT** [o365soa/Scripts#28]
invoke-mggraph cmdlet no longer has -authentication param
![Screenshot 2024-02-08 085008](https://github.com/o365soa/Scripts/assets/55812994/824f41ee-b368-4c2a-b4d4-92558550d6fd)

**Comment by sbueffel** [comment]
This was resolved after the script was updated to require v2 of the SDK.
